# Generated by Django 3.2.3 on 2021-06-26 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_obra'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='obra',
            table='obra',
        ),
    ]
